
/**
 * Do not edit directly, this file was auto-generated.
 */



package se.seb.gds

enum class GdsTypography {
    DISPLAY2XL,
    DISPLAYXL,
    DISPLAYL,
    DISPLAYM,
    DISPLAYS,
    HEADINGXL,
    HEADINGL,
    HEADINGM,
    HEADINGS,
    HEADINGXS,
    HEADING2XS,
    PREAMBLE2XL,
    PREAMBLEXL,
    PREAMBLEL,
    PREAMBLEM,
    PREAMBLES,
    PREAMBLEXS,
    DETAILBOOKM,
    DETAILBOOKS,
    DETAILBOOKXS,
    DETAILREGULARM,
    DETAILREGULARS,
    DETAILREGULARXS,
    BODYMEDIUMM,
    BODYMEDIUMS,
    BODYBOOKM,
    BODYBOOKS,
    BODYREGULARL,
    BODYREGULARM,
    BODYREGULARS,
    BODYITALICM,
    BODYITALICS,
}
